- hosts: localhost
  tasks:
  - name: Update apt
    become: true
    apt:
      name: "*"
      state: latest
  - name: Basic usage
    debug:
      msg: "'{{ lookup('env', 'HOME') }}' is the HOME environment variable."

  - name: Example how to set default value if the variable is not defined
    debug:
      msg: "'{{ lookup('env', 'USR') | default('nobody', True) }}' is the user."