- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]
    
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check that the somefile.conf exists
  stat:
    path: /home/treramey/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: treramey

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Install space theme
  ansible.builtin.git:
    repo: 'https://github.com/spaceship-prompt/spaceship-prompt'
    dest: "~/.oh-my-zsh/themes/spaceship-prompt"
    shell: "ln -s '$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme' '$ZSH_CUSTOM/themes/spaceship.zsh-theme'"
  tags: *tags_for_zsh_tasks
